---
# Couleurs de l'interface
colors:
  library_text: "#ffffff"
  library_selected: "#cb28cb"
  library_text_selected: "#181318"
  volume: "#cb28cb"
  volume_fond: "#888888"
  song_tittle: "#ffffff"
  border_window: "#cb28cb"
  progress_bar: "#ff00ff"
  progress_bar_fond: white
  text_primary: white
  text_secondary: "#cb28cb"
  selected_text: "#181318"
  background: "#1E1E1E"
  header_background: "#282828"
  background_button: "#333333"
  selected_playlist: "#cb28cb"
  selected_text_playlist: "#181318"
  playlist_header_line: "#ffffff"
  player_button: "#ffffff"
  player_button_hover : "#cb28cb"
  button_stop: "#ffffff"
  button_stop_hover: "#cb28cb"
  button_next: "#ffffff"
  button_next_hover: "#cb28cb"
  button_prev: "#ffffff"
  button_prev_hover: "#cb28cb"
  button_pause: "#ffffff"
  button_close: "#ffffff"
  button_close_hove: "#cb28cb"
  button_maximize: "#ffffff"
  button_maximize_hove: "#cb28cb"
  button_minimize: "#ffffff"
  button_minimize_hove: "#cb28cb"

  colonne_text_colors:
    track: "#FFA500"
    title: "#cb28cb"
    artist: "#2876cb"
    album: "#39cb28"
    time: "#c9cb28"
    pos: "#FFA500"

#hie_colonne_playlist:
#  - ID
# Style de police et tailles
font:
  family: "Montserrat"
  size: 10


# Largeur des colonnes
#column_widths:
#  track: 50
#  title: 200
#  artist: 150
#  album: 100
#  time: 60

# Comportements et raccourcis
behavior:
  allow_column_resizing: true
  stretch_columns:
    - "title"
    - "album"
  shortcuts:
    play_pause: "Space"
    next: "Right"
    previous: "Left"